### ISSUE TITLE
Everyone needs to add their own snapsvisa

### ISSUE THREAD

**Issue by Kevintrf** [prowrestling/snapsvisor#3]
Issue will be closed once everyone has added at least one song

**Comment by PandaFood** [comment]
Detta känns diskriminerande. Varför behöver inte alla göra det, som typ Anna eller Filip?

**Comment by Kevintrf** [comment]
> Detta känns diskriminerande. Varför behöver inte alla göra det, som typ Anna eller Filip?

Alla måste. Däremot så har inte alla assignats pga lathet/avsaknad av githubkonton.

**Comment by Kevintrf** [comment]
orkar inte längre se den här issuen på github hemskärmen
